# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72f19b28594307e1d1e2d54e61789085b08cdbc25c75ea5c3be1c2d6516232e5431503ff1c0ab9e20280cc7b58f516a56f80a4704cc0f8eef9730e26d40ab0fd

test:
  secret_key_base: dd0f0dad9862eb6f5cb10a8513b7f9802e69a2be8ceddd803ec181a895e0382650e05be12331ded1d2796eb97b7b242a053e25847cbc632193da2eababec8940

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
